name = "nda-tracker"
main = "nda-tracker-worker.js"
compatibility_date = "2025-05-11"

account_id = "f07be5f84583d0d100b05aeeae56870b"

[env]
ENVIRONMENT = "production"

[env.production]
name = "nda-tracker"
route = "partners.mobleysoft.com/abt/*"
zone_id = "f9ec6bb9f8b3f3e3c8b3f3e3c8b3f3e3"
