name = "getdomains"
main = "getdomains-worker.js"
compatibility_date = "2025-05-11"

account_id = "f07be5f84583d0d100b05aeeae56870b"

[[d1_databases]]
binding = "HYDRA_DB"
database_name = "mascom-core"
database_id = "a737193b-f898-497f-9fe5-ec39d464f0bf"

[env.production]
name = "getdomains"

[[env.production.d1_databases]]
binding = "HYDRA_DB"
database_name = "mascom-core"
database_id = "a737193b-f898-497f-9fe5-ec39d464f0bf"
